# Generated by Django 3.2.8 on 2021-11-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('Incident_Dept', models.CharField(max_length=100)),
                ('dateandtime', models.DateTimeField()),
                ('incident_location', models.TextField(max_length=500)),
                ('initial_severity', models.CharField(max_length=100)),
                ('suspected_cause', models.TextField(max_length=500)),
                ('immediate_action_taken', models.TextField(max_length=500)),
                ('sub_incident_type', models.CharField(max_length=100)),
            ],
        ),
    ]
